import { StyleSheet } from 'react-native';

const styles = StyleSheet.create({
    container: {
        padding: 18,
    },
    error: {
        color: 'red',
    },
    labelText: {
        marginTop: 30,
        marginBottom: 10,
    },
    labelText1: {
        padding: 5,
        fontSize: 20,
        fontWeight: 'bold',
        marginBottom: 2,
    },
    labelText2: {
        marginLeft: 5,
        marginTop: 5,
        fontSize: 20,
        fontWeight: 'bold',
    },
    labelText4: {
        marginLeft: 5,
        fontSize: 13,
        marginBottom: 5,

    },
    labelTextBelow: {
        padding: 5,
        fontSize: 20,
        fontWeight: 'bold',
        marginBottom: 2,
        color: 'red',
    },
    labelTextUpper: {
        padding: 5,
        fontSize: 20,
        fontWeight: 'bold',
        marginBottom: 2,
        color: 'orange',
    },
    focusedValueContainer: {
        flex: 0,
        height: 90,
        width: 250,
        marginTop: 5,
        marginBottom: 10,
        paddingHorizontal: 20,
        backgroundColor: 'orange',
        borderRadius: 5,
        padding: 5,
        borderRadius: 10,
        borderWidth: 2,
        borderColor: '#cccccc',
    },
    focusedValueText2: {
        fontSize: 18,
        color: 'white',
        fontWeight: 'bold',
        marginTop: 7,
        padding: 5,
    },

    focusedValueText: {
        fontSize: 14,
        color: 'white',
        fontWeight: 'bold',
    },
    Container: {
        backgroundColor: '#f0f8ff',
        borderRadius: 10,
        borderWidth: 2,
        borderColor: '#cccccc',
        padding: 10,
        marginBottom: 10,

    },
    chartContainer: {
        backgroundColor: '#f0f8ff',
        borderRadius: 10,
        borderWidth: 2,
        borderColor: '#cccccc',
        padding: 10,
        marginBottom: 30,

    },
    legendContainer: {
        flexDirection: 'row',
        marginTop: 10,
        padding: 5,
        marginLeft: 40,
    },
    legendContainerPie: {
        flexDirection: 'row',
        flexWrap: 'wrap',
        justifyContent: 'space-between',
        marginTop: 10,
        padding: 5,
    },
    legendItem: {
        flexDirection: 'row',
        alignItems: 'center',
        marginRight: 20,
    },
    legendItemPie: {
        flexDirection: 'row',
        alignItems: 'center',
        marginRight: 5,
    },
    colorBox: {
        width: 30,
        height: 10,
        marginRight: 5,
        padding: 5,
    },
    colorBoxPie: {
        width: 20,
        height: 10,
        marginRight: 5,
        padding: 0,
    },
    pieContainer: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        marginBottom: 10,

    },
    pieChartContainer: {
        padding: 10,
        backgroundColor: '#f0f8ff',
        borderRadius: 10,
        borderWidth: 2,
        borderColor: '#cccccc',
        flex: 1,
        alignItems: 'center',
    },
    buttonContainer: {
        flexDirection: 'row',
        justifyContent: 'space-around',
        marginVertical: 10,
    },
    activeButton: {
        backgroundColor: '#177AD5',
    },
    buttonText: {
        color: 'black',
        fontWeight: 'bold',
    },
    tempContainer: {
        flexDirection: 'row',
        flexWrap: 'wrap',
        padding: 10,
        backgroundColor: '#f0f8ff',
        borderRadius: 10,
        borderWidth: 2,
        borderColor: '#cccccc',
        flex: 1,
        alignItems: 'Left',
        marginBottom: 5,
    },
    tempTextContainer: {
        flexDirection: 'row',
        alignItems: 'center',
        marginRight: 5,

    },
    temperatureText: {
        padding: 5,
        fontSize: 22,
        fontWeight: 'bold',
    },
    header: {
        fontSize: 24,
        marginBottom: 5,
        fontWeight: 'bold',
        textAlign: 'center',
    },
    header2: {
        fontSize: 20,
        marginBottom: 15,
        fontWeight: 'bold',
    },
    label: {
        fontSize: 16,
        marginTop: 10,
        flex: 1,
        fontWeight: 'bold',
        marginRight: 5,
        marginLeft: 10,
    },
    input: {
        height: 50,
        borderWidth: 1,
        borderColor: '#ccc',
        padding: 10,
        borderRadius: 5,
        marginTop: 5,
        backgroundColor: '#f0f0f0',
        flex: 2,
        marginRight: 5,
    },
    input2: {
        height: 50,
        borderWidth: 1,
        borderColor: '#007BFF',
        padding: 10,
        borderRadius: 5,
        marginTop: 5,
        marginRight: 5,
        backgroundColor: '#fff',
        flex: 2,
    },
    row: {
        flexDirection: 'row',
        alignItems: 'center',
        marginBottom: 15,
    },
    button: {
        backgroundColor: '#28a745',
        paddingVertical: 12,
        borderRadius: 30,
        alignItems: 'center',
        marginTop: 10,
        marginBottom: 10,
    },
    buttonText: {
        color: '#FFFFFF',
        fontSize: 20,
        fontWeight: 'bold',
    },
    button2: {
        borderColor: 'green',
        borderWidth: 3,
        backgroundColor: '#FFF',
        paddingVertical: 12,
        borderRadius: 30,
        alignItems: 'center',
        marginTop: 10,
        marginBottom: 10,
    },
    buttonText2: {
        color: 'green',
        fontSize: 20,
        fontWeight: 'bold',
    },
    errorText: {
        color: 'red',
        marginTop: 5,
        marginBottom: 30,
        textAlign: 'center',
        fontSize: 20,
    },
    errorText1: {
        color: 'red',
        marginTop: 5,
        marginBottom: 5,
        textAlign: 'center',
        fontSize: 16,
    },
    picker: {
        height: 50,
        width: 193,
        backgroundColor: '#f0f0f0',
        borderWidth: 3,
        borderColor: '#ccc',
        borderRadius: 5,
        marginTop: 5,
        marginRight: 12,
        marginLeft: 13,
    },
    picker2: {
        height: 50,
        width: 193,
        backgroundColor: 'white',
        borderWidth: 3,
        borderColor: '#007BFF',
        borderRadius: 5,
        marginTop: 5,
        marginRight: 12,
        marginLeft: 13,
    },
    picker12: {
        height: 50,
        width: 193,
        backgroundColor: '#f0f0f0',
        borderWidth: 3,
        borderColor: '#ccc',
        borderRadius: 5,
        marginTop: 5,
        marginRight: 12,
        marginLeft: 15,
    },
    picker22: {
        height: 50,
        width: 193,
        backgroundColor: 'white',
        borderWidth: 3,
        borderColor: '#007BFF',
        borderRadius: 5,
        marginTop: 5,
        marginRight: 12,
        marginLeft: 15,
    },
    picker11: {
        height: 50,
        width: 100,
        backgroundColor: '#f0f0f0',
        borderWidth: 3,
        borderColor: '#ccc',
        borderRadius: 5,
        marginTop: 5,
        marginRight: 12,
        marginLeft: 5,

    },
    picker21: {
        height: 50,
        width: 100,
        backgroundColor: 'white',
        borderWidth: 3,
        borderColor: '#007BFF',
        borderRadius: 5,
        marginTop: 5,
        marginRight: 12,
        marginLeft: 5,

    },
});

export default styles;